---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: mdr/busybox-workload
  labels:
    app: busybox-workload
  name: busybox-sub
spec:
    channel: ramen-samples/ramen-gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: busybox-placement
