---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-world
  labels:
    appname: hello-world
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-external-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-job
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "Hello, World!"
          restartPolicy: OnFailure
          volumeMounts:
          - mountPath: /mnt/test
            name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: hello-world
          readOnly: false
