---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: busybox-placement
  namespace: test-app
  labels:
    app: test-app
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterReplicas: 1
  schedulerName: "ramen"
