---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: mdr/busybox-sample/busybox/app
  labels:
    app: test-app
  name: busybox-sub
  namespace: test-app
spec:
    channel: ramen-samples/ramen-gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: busybox-placement
