apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appname: busybox-49
  name: busybox-49
spec:
  selector:
    matchLabels:
      workload: busybox-49
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload: busybox-49
    spec:
      containers:
      - command:
        - sh
        - -c
        - while true; do echo $(date) | tee -a /mnt/test/outfile; sync; sleep 3; done
        image: docker.io/ppc64le/busybox:latest
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /mnt/test
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: busybox-pvc-49
          readOnly: false
