apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appname: busybox
  name: busybox-cephfs
  namespace: busybox-sample
spec:
  selector:
    matchLabels:
      workload: busybox-cephfs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload: busybox-cephfs
    spec:
      containers:
      - command: ["/bin/sh", "-c"]
        image: quay.io/vcppds7878/busybox:latest
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /mnt/test
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: busybox-cephfs-pvc
          readOnly: false
