apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appname: busybox
  name: busybox-rbd
  namespace: busybox-sample
spec:
  selector:
    matchLabels:
      workload: busybox-rbd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload: busybox-rbd
    spec:
      containers:
      - command: ["/bin/sh", "-c"]
        args:
          - wget  https://raw.githubusercontent.com/red-hat-storage/ocs-workloads/master/rdr/busybox/scripts/kernel_untar.sh -O /mnt/test/kernel_untar.sh;
            wget https://raw.githubusercontent.com/red-hat-storage/ocs-workloads/master/rdr/busybox/scripts/kernel_untar_integrity_check.sh  -O /mnt/test/kernel_untar_integrity_check.sh;
            chmod +x /mnt/test/kernel_untar.sh; chmod +x /mnt/test/kernel_untar_integrity_check.sh;
            /mnt/test/kernel_untar.sh
        image: quay.io/vcppds7878/busybox:latest
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /mnt/test
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: busybox-rbd-pvc
          readOnly: false
