apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appname: busybox
  name: busybox-rbd
  namespace: busybox-sample
spec:
  selector:
    matchLabels:
      workload: busybox-rbd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload: busybox-rbd
    spec:
      containers:
      - command: ["/bin/sh", "-c"]
        args:
          - wget "https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.14.tar.xz" && \
            tar -xvf linux-4.14.tar.xz
        image: quay.io/vcppds7878/busybox:latest
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /mnt/test
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: busybox-rbd-pvc
          readOnly: false
